### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by aaferna** [parzibyte/plugin-ticket-js#3]
Dos preguntas
1) Existe algun limite (aparte de tu nombre en el tiket) de impresion o por el estilo?
2) Porque me sele simbolos creo chinos, en la cabeza del tiket?

**Comment by parzibyte** [comment]
Hola

1. No. Puedes usar el plugin en donde quieras y como quieras, sin límite alguno
2. Puede que sea tu modelo especifico de impresora, ya que no todas implementan el lenguaje ESC POS del mismo modo

**Comment by aaferna** [comment]
Gracias por la pronta respuesta. Otra consulta, ya que tu plugin me crea un server:

1) Como ejecuta y/o que es? Node?
2) Puedo usar ese server url para imprimir desde otro pc con https?

**Comment by aaferna** [comment]
y porfavor, para que servia "setEmphasize"

**Comment by parzibyte** [comment]
**Como ejecuta y/o que es? Node?** Es un servidor escrito en Go
**Puedo usar ese server url para imprimir desde otro pc con https?** así es, pero me parece que hay problemas con HTTPS, tendría que ser sin HTTPS, poniendo solo la IP del servidor, obviamente con el puerto y todo eso
**y porfavor, para que servia "setEmphasize"** Me parece que es para que las letras sean más negritas

**Comment by aaferna** [comment]
Genio muchas gracias. Te nombrarse en mi proyecto ya que es más que merecido tu trabajo.

Una última pregunta. ¿Podemos hacer q ejecute https?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by parzibyte** [comment]
Gracias a ti por tus comentarios.
Se puede hacer https, pero es un poco complejo por eso de los certificados, e implicaría un trabajo personalizado; si te interesa puedes enviarme un mensaje privado en https://parzibyte.me/blog/contacto
