### ISSUE TITLE
Does the examples working?

### ISSUE THREAD

**Issue by pcsantana** [parzibyte/plugin-ticket-js#6]
I tried to use the live examples to test, but I got a error, even the v1 or v2 plugin.

v1 I tried to use this:
https://parzibyte.github.io/plugin-ticket-js/en/examples/ticket/index.html

but I got the error in console:
`Response: Error en el servidor: sql: no rows in result set`

With v2, I installed the exe and tried to use this page:
https://parzibyte.github.io/ejemplos-plugin-impresoras-termicas-v2/ticket/

but I got the error in console:
`Error. La respuesta es: Error en el servidor: json: cannot unmarshal object into Go value of type []main.OperacionTicket`

I am using windows 7 64bits, and a POS 58 printer.

PS: the printer is installed and tested.

Thank you!

**Comment by parzibyte** [comment]
Yes, the examples work. For V1 the error is documented in the faq: https://parzibyte.github.io/plugin-ticket-js/en/#faq by the way remember that you can use the imprimirEnImpresora method
And for V2, the examples are here: https://parzibyte.github.io/ejemplos-plugin-impresoras-termicas-v2/

**Comment by pcsantana** [comment]
Hi @parzibyte !
Thank you for answering. 
About v1 error I am a little confused, because the printer is listed and if I try to print the page (ctrl+P), it works.
But If I try to set as default or tried to printer, it's not working.

See the screenshot bellow:
https://drive.google.com/file/d/1KbFN5VgY6ls5pdWLqJR3Ld9zQn5BQ4l1/view?usp=sharing
https://drive.google.com/file/d/17Gcz0v7Hz3XN-JqsBA9N7ThLYvipyL27/view?usp=sharing

Thanks in advance!

**Comment by parzibyte** [comment]
Hi. Is the printer shared from the control panel? Also, please check if the plugin has rights to create some files (it needs an SQLite database that is created automatically but it needs write permissions on the system).

**Comment by pcsantana** [comment]
Thank you!
It was my mistake! I didnt share the printer.
Now it works!
I have a doubt about the plans. 
These plans (https://parzibyte.me/plugin-impresora-termica/planes/) is applied for v1 too? In the v1 FAQ page shows the price 25 dollars.

**Comment by parzibyte** [comment]
Glad to help! And regarding to your question: plans are for v2, for v1 is a one-time payment of 25 USD.

**Comment by pcsantana** [comment]
Ok!
I will try now to code in my app with the free version. If it works like I expect I will contact you for the premium version.
Thank you.
