### ISSUE TITLE
I found this error when I'm printing

### ISSUE THREAD

**Issue by pradeep955734** [parzibyte/plugin-ticket-js#7]
![WhatsApp Image 2021-09-16 at 4 38 07 AM](https://user-images.githubusercontent.com/80516938/133885935-db1c28cc-22db-4aa1-bdcd-5b6f32be1e85.jpeg)

**Comment by parzibyte** [comment]
https://parzibyte.me/blog/2021/11/16/solucion-error-servidor-sql-no-rows-in-result-set-plugin-impresora-termica/
